
### Get Article List (external)
GET http://localhost:3000/api/external

### Get Article List (internal)
GET http://localhost:3000/api/articles

### Get an article by id
GET http://localhost:3000/api/articles/2

### Post an article
POST http://localhost:3000/api/articles/add
Content-Type: application/json

{
    "title" : "Article Title",
    "description" : "Article TEXT"
}


